/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifihada_teechecker_MobiCore */

#ifndef _Included_com_ifihada_teechecker_MobiCore
#define _Included_com_ifihada_teechecker_MobiCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifihada_teechecker_MobiCore
 * Method:    native_getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ifihada_teechecker_MobiCore_native_1getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
